version: '3.8'

services:
  backend:
    image: localhost:5000/local-registry-node
    container_name: lr-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    image: localhost:5000/local-registry-postgres
    container_name: lr-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d docker-test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data: