FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

#---------------------------------------

FROM node:20-alpine

WORKDIR /app

RUN mkdir -p /app/logs && chown -R node:node /app/logs

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./

COPY --from=builder /app/src ./src

COPY --from=builder /app/db.js ./
COPY --from=builder /app/app.js ./

EXPOSE 3000
USER node

CMD ["node", "app.js"]