name: Continuous Integration & Deployment

on:
  push:
    branches:
      - staging

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          # 🏆 Step 1: Tell setup-node where your lockfiles live
          cache-dependency-path: '**/package-lock.json'

      # 🏆 Step 2: Install Backend Dependencies
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      # 🏆 Step 3: Test / Build Backend
      - name: Build Backend
        working-directory: ./backend
        run: npm run build

      # 🏆 Step 4: Install Frontend Dependencies
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci

      # 🏆 Step 5: Test / Build Frontend
      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute Deploy Script on Staging Server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.STAGING_SERVER_HOST }}
          username: ${{ secrets.STAGING_SERVER_USER }}
          key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          port: 22
          script_path: scripts/deploy/deploy-staging.sh
