name: Local Compose Build and Push

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  compose-pipeline:
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate .env File
        env:
          PORT: ${{ secrets.PORT }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: |
          cat <<EOF > .env
          PORT=${PORT}
          POSTGRES_USER=${POSTGRES_USER}
          POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          POSTGRES_DB=${POSTGRES_DB}
          POSTGRES_HOST=${POSTGRES_HOST}
          VITE_API_URL=${VITE_API_URL}
          EOF

          # Optional: Mask sensitive passwords if printing for debugging
          echo "--- Generated .env File ---"
          cat .env

      - name: Build Images
        run: docker compose build

      - name: Push Images to Local Registry
        run: docker compose push

      - name: Run Stack
        run: docker compose up -d
